// This file is auto-generated by `ember build`.
// You should not modify it.

var App = window.App = require('./config/app');
require('./templates');


App.ApplicationController = require('./controllers/application_controller');

require('./config/routes');

module.exports = App;

